### DISCUSSION TITLE
invalid mount config for type "bind": bind source path does not exist:

### DISCUSSION THREAD

**Discussion by marcbaier** [jasonacox/Powerwall-Dashboard#166] [Q&A]
Hi - i followed the installation instructions and while going through the setup process, I am getting the following error message:

Running Docker Compose...
[+] Running 0/0
 ⠋ Container influxdb  Creating                                            0.0s
Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /users/marcbaier/powerwall-dashboard/influxdb.conf

What could the issue be ?

**Comment by jasonacox** [comment]
That would indicate that you are missing config files in your /users/marcbaier/powerwall-dashboard folder.  Can you check that directory for us?

```bash
ls /users/marcbaier/powerwall-dashboard/
```

**Reply by marcbaier** [reply]
Thanks for the very quick reply - here's a screenshot of the directory: 
<img width="1018" alt="Screen Shot 2023-01-31 at 17 08 50 PM" src="https://user-images.githubusercontent.com/97667985/215815650-8f4e2de2-56a0-41fe-992e-940adb2f0bce.png">

**Reply by marcbaier** [reply]
<img width="685" alt="Screen Shot 2023-01-31 at 22 52 47 PM" src="https://user-images.githubusercontent.com/97667985/215892072-47a4dcb7-a967-4c4b-b9c4-01c46c0fb954.png">

**Reply by jasonacox** [reply]
Thank you!  Can you give me a few more pieces of info:

```bash
cat VERSION

git status

docker --version

docker-compose --version # this may fail depending on version of docker

cat powerwall.yml
```

**Comment by marcbaier** [comment]
Hi Jason

Here we go:

Cat version: 2.7.1
Git status:
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   dashboard.json
	modified:   dashboards/dashboard-animation.json
	modified:   dashboards/dashboard-grid.json
	modified:   dashboards/dashboard-new.json
	modified:   dashboards/dashboard-no-animation.json
	modified:   dashboards/dashboard-simple.json
	modified:   dashboards/dashboard.json
	modified:   influxdb/influxdb.sql
	modified:   telegraf.conf
	modified:   tz

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	compose.env
	grafana.env
	telegraf.local

no changes added to commit (use "git add" and/or "git commit -a")

Docker version: Docker version 20.10.22, build 3a2c30b

Docker Compose version v2.15.1

cat powerwall.yml:
```yml
version: "3.5"

services:
    influxdb:
        image: influxdb:1.8
        container_name: influxdb
        hostname: influxdb
        restart: always
        volumes:
            - type: bind
              source: ./influxdb.conf
              target: /etc/influxdb/influxdb.conf
              read_only: true
            - type: bind
              source: ./influxdb
              target: /var/lib/influxdb
        ports:
            - target: 8086
              published: 8086
              mode: host

    pypowerwall:
        image: jasonacox/pypowerwall:latest
        container_name: pypowerwall
        hostname: pypowerwall
        restart: always
        user: "1000:1000"
        ports:
            - target: 8675
              published: 8675
              mode: host
        env_file:
            - pypowerwall.env

    telegraf:
        image: telegraf:latest
        container_name: telegraf
        hostname: telegraf
        restart: always
        user: "1000:1000"
        command: [
            "telegraf", 
            "--config",  
            "/etc/telegraf/telegraf.conf", 
            "--config-directory",
            "/etc/telegraf/telegraf.d"
        ]
        volumes:
            - type: bind
              source: ./telegraf.conf
              target: /etc/telegraf/telegraf.conf
              read_only: true
            - type: bind
              source: ./telegraf.local
              target: /etc/telegraf/telegraf.d/local.conf
              read_only: true            
        depends_on:
            - influxdb
            - pypowerwall

    grafana:
        image: grafana/grafana:9.1.2-ubuntu
        container_name: grafana
        hostname: grafana
        restart: always
        user: "${GRAFANAUSER}"
        volumes:
            - type: bind
              source: ./grafana
              target: /var/lib/grafana
        ports:
            - target: 9000
              published: 9000
              mode: host
        env_file:
            - grafana.env
        depends_on:
            - influxdb

    weather411:
        image: jasonacox/weather411:latest
        container_name: weather411
        hostname: weather411
        restart: always
        user: "1000:1000"
        volumes:
            - type: bind
              source: ./weather
              target: /var/lib/weather
              read_only: true
        ports:
            - target: 8676
              published: 8676
              mode: host
        environment:
            - WEATHERCONF=/var/lib/weather/weather411.conf
        depends_on:
            - influxdb

```

**Reply by jasonacox** [reply]
What version of MacOS are you using?

> Docker Compose version v2.15.1

I'm on MacOS but have been testing v1.29.2 with no problem.  I'll try to get v2 and try to replicate the same error you get.

**Reply by marcbaier** [reply]
I am using MacOS Ventura 13.1

**Comment by jasonacox** [comment]
Ah.. this may be it.

Try to run `docker compose version` (I get Docker Compose version v2.2.3)

If that works, try:

```bash
docker compose -f powerwall.yml up -d
```

**Reply by marcbaier** [reply]
docker compose version gives me: v2.15.1

**Reply by marcbaier** [reply]
I executed the command and this is the result: 
Marcs-5k-iMac:powerwall-dashboard marcbaier$ docker compose -f powerwall.yml up -d
WARN[0000] The "GRAFANAUSER" variable is not set. Defaulting to a blank string. 
[+] Running 5/5
 ⠿ Container influxdb     Started                                          0.9s
 ⠿ Container grafana      Started                                          2.1s
 ⠿ Container weather411   Started                                          2.1s
 ⠿ Container telegraf     Started                                          2.0s
 ⠿ Container pypowerwall  Started                                          0.8s
Marcs-5k-iMac:powerwall-dashboard marcbaier$

**Comment by marcbaier** [comment]
Ok I now got the /.setup.sh working: 
Running Docker Compose...
[+] Running 5/5
 ⠿ Container influxdb     Running                                          0.0s
 ⠿ Container weather411   Running                                          0.0s
 ⠿ Container grafana      Running                                          0.0s
 ⠿ Container pypowerwall  Started                                         10.9s
 ⠿ Container telegraf     Started                                          1.2s
-----------------------------------------
Waiting for InfluxDB to start...
 up!
Setup InfluxDB Data for Powerwall...
2023/02/02 09:43:36 error: error parsing query: unable to find time zone Europe
2023/02/02 09:43:36 error: error parsing query: unable to find time zone Europe
Fetching local weather...
weather411
------------------[ Final Setup Instructions ]-----------------

Open Grafana at http://localhost:9000/ ... use admin/admin for login.

Follow these instructions for *Grafana Setup*:

* From 'Configuration\Data Sources' add 'InfluxDB' database with:
  - Name: 'InfluxDB'
  - URL: 'http://influxdb:8086'
  - Database: 'powerwall'
  - Min time interval: '5s'
  - Click "Save & test" button

* From 'Configuration\Data Sources' add 'Sun and Moon' database with:
  - Name: 'Sun and Moon'
  - Enter your latitude and longitude (tool here: https://bit.ly/3wYNaI1 )
  - Click "Save & test" button

What do I need to put in as "timezone" ?

**Reply by marcbaier** [reply]
Dude I got it working ! 

<img width="1691" alt="Screen Shot 2023-02-02 at 10 53 53 AM" src="https://user-images.githubusercontent.com/97667985/216292217-50b24572-4833-4419-9165-a511e1af68da.png">

**Reply by marcbaier** [reply]
now that I've got this running I need to figure out how to set this up on my Synology NAS as my Mac is not always on....

**Reply by jasonacox** [reply]
Awesome job @marcbaier!!!!  Congratulations!  🎉 

What was the trick that you found that got it working for you (in case others find this issue or we can fix the setup script to help)?

Also, for timezone, I assume you figured it out, but a table of valid timezones is here: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

**Comment by marcbaier** [comment]
the command: docker compose -f powerwall.yml up -d - fixed it for me. 
A lot of panels are empty in my dashboard though - do you know why that might be ? 
<img width="1400" alt="Screen Shot 2023-02-03 at 08 15 35 AM" src="https://user-images.githubusercontent.com/97667985/216536216-afc38f78-b2fe-4c0b-b070-79aeadcec550.png">

**Reply by jasonacox** [reply]
I assume that means that `docker-compose -f powerwall.yml up -d` (with a dash) was the problem.

The missing data is due to the fact that the setup.sh script didn't finish. Specifically, the Influxdb import to set up the continuous queries that builds the data for the graph. Run this:

```bash
docker exec --tty influxdb sh -c "influx -import -path=/var/lib/influxdb/influxdb.sql"
```

If you set up for local weather data feed, you would restart that too:

```bash
docker restart weather411
```

Let me know if that works!

If you are willing to help troubleshoot, I would like to figure out why your setup didn't work. The setup uses the file `compose-dash.sh` to manage docker compose.  It's designed to first try `docker-compose` and if it is not available on your system, it uses `docker compose` (no dash).  Can you run this:

```bash
# location of docker
which docker
which docker-compose

# details on file
ls -l `which docker-compose`
```

**Reply by marcbaier** [reply]
Ok I ran both scripts you mentioned above. Here is the data you requested:

which docker: /usr/local/bin/docker
which docker-compose: /usr/local/bin/docker-compose

I was not able to run "ls -l 'which docker compose'. 
ls -l docker-compose returns this:
lrwxr-xr-x  1 root  wheel  62 Jan 13  2022 docker-compose -> /Applications/Docker.app/Contents/Resources/bin/docker-compose

**Reply by jasonacox** [reply]
Thanks @marcbaier ! 

> I was not able to run "ls -l 'which docker compose'.

No worries, you got what I wanted. The single quote (') is actually the backquote (`) which is a way to tell the shell to run the command and insert the output as an argument.

It still puzzles me why 'docker-compose' on your setup is not behaving like 'docker compose'.  Would you mind having each version validate the config file to see what they say?

```bash
# validate and view config file
docker-compose -f powerwall.yml config 

# validate and view config file
docker compose -f powerwall.yml config 
```

Both should only produce a warning similar to this with a list of the config file:
WARN[0000] The "GRAFANAUSER" variable is not set. Defaulting to a blank string.

Anyway, thanks for the additional help.  Are you seeing data in your graphs now?

**Reply by marcbaier** [reply]
here is the powerwall.yml:
```yml
WARN[0000] The "GRAFANAUSER" variable is not set. Defaulting to a blank string. 
name: powerwall-dashboard
services:
  grafana:
    container_name: grafana
    depends_on:
      influxdb:
        condition: service_started
    environment:
      GF_ANALYTICS_CHECK_FOR_UPDATES: "false"
      GF_ANALYTICS_REPORTING_ENABLED: "false"
      GF_INSTALL_PLUGINS: grafana-piechart-panel, natel-plotly-panel, blackmirror1-singlestat-math-panel,
        btplc-trend-box-panel, marcuscalidus-svg-panel, michaeldmoore-multistat-panel,
        https://github.com/yesoreyeram/yesoreyeram-boomtable-panel/releases/download/v1.5.0-alpha.3/yesoreyeram-boomtable-panel-1.5.0-alpha.3.zip;yesoreyeram-boomtable-panel,
        ryantxu-ajax-panel, grafana-influxdb-flux-datasource, fetzerch-sunandmoon-datasource,
        andig-darksky-datasource, simpod-json-datasource
      GF_PANELS_DISABLE_SANITIZE_HTML: "true"
      GF_PATHS_PROVISIONING: /var/lib/grafana/provisions
      GF_SERVER_HTTP_PORT: "9000"
    hostname: grafana
    image: grafana/grafana:9.1.2-ubuntu
    networks:
      default: null
    ports:
    - mode: host
      target: 9000
      published: "9000"
    restart: always
    volumes:
    - type: bind
      source: /Users/marcbaier/Powerwall-Dashboard/grafana
      target: /var/lib/grafana
  influxdb:
    container_name: influxdb
    hostname: influxdb
    image: influxdb:1.8
    networks:
      default: null
    ports:
    - mode: host
      target: 8086
      published: "8086"
    restart: always
    volumes:
    - type: bind
      source: /Users/marcbaier/Powerwall-Dashboard/influxdb.conf
      target: /etc/influxdb/influxdb.conf
      read_only: true
    - type: bind
      source: /Users/marcbaier/Powerwall-Dashboard/influxdb
      target: /var/lib/influxdb
  pypowerwall:
    container_name: pypowerwall
    environment:
      PW_DEBUG: "no"
      PW_EMAIL: XXXXX
      PW_HOST: XXXXX
      PW_PASSWORD: XXXXX
      PW_TIMEZONE: Europe/Zurich
      TZ: Europe/Zurich
    hostname: pypowerwall
    image: jasonacox/pypowerwall:latest
    networks:
      default: null
    ports:
    - mode: host
      target: 8675
      published: "8675"
    restart: always
    user: 1000:1000
  telegraf:
    command:
    - telegraf
    - --config
    - /etc/telegraf/telegraf.conf
    - --config-directory
    - /etc/telegraf/telegraf.d
    container_name: telegraf
    depends_on:
      influxdb:
        condition: service_started
      pypowerwall:
        condition: service_started
    hostname: telegraf
    image: telegraf:latest
    networks:
      default: null
    restart: always
    user: 1000:1000
    volumes:
    - type: bind
      source: /Users/marcbaier/Powerwall-Dashboard/telegraf.conf
      target: /etc/telegraf/telegraf.conf
      read_only: true
    - type: bind
      source: /Users/marcbaier/Powerwall-Dashboard/telegraf.local
      target: /etc/telegraf/telegraf.d/local.conf
      read_only: true
  weather411:
    container_name: weather411
    depends_on:
      influxdb:
        condition: service_started
    environment:
      WEATHERCONF: /var/lib/weather/weather411.conf
    hostname: weather411
    image: jasonacox/weather411:latest
    networks:
      default: null
    ports:
    - mode: host
      target: 8676
      published: "8676"
    restart: always
    user: 1000:1000
    volumes:
    - type: bind
      source: /Users/marcbaier/Powerwall-Dashboard/weather
      target: /var/lib/weather
      read_only: true
networks:
  default:
    name: powerwall-dashboard_default
```
