### DISCUSSION TITLE
TrueNas Scale and powerwall-dashboard

### DISCUSSION THREAD

**Discussion by Craig-G-NZ** [jasonacox/Powerwall-Dashboard#324] [General]
Hi Jason, I am currently using Truenas Core, and a VM on the box to host my powerwall-dashboard and its working really well, but i'd like to move to truenas scale which has built in containerisation etc. would it be possible to break this down into bite sized chucks to do this? I'm thinking is it possible to create a Kubernetes image that contains all the parts i need to be able to run it?

**Comment by jasonacox** [comment]
Hi @Craig-G-NZ !  This is absolutely possible. I don't have a Truenas device so I can't help develop this, but I'm sure others out there would appreciate hearing your adventure. 

To start, I suspect Truenas requires you to define each container. You can look at the `powerwall.yml` file as the key setup file to inform how to set up the rest (it references environmental config files you will need to use as well). 

I asked ChatGPT to convert our `powerwall.yml` docker-compose file into a script with separate docker runs. I then asked it if it could convert it to a kubernetes manifest.  This may help with your adventure. To be fair, I'm sure there is some errors here but it was rather impressive to see what this AI could do.

See the chat session:
https://chat.openai.com/share/c70ac870-b8c9-4d58-b1c5-47d5f6e49332

The conversion to `docker run` scripts:
```bash
#!/bin/bash

# Run InfluxDB container
docker run -d \
    --name influxdb \
    --hostname influxdb \
    --restart always \
    -v $(pwd)/influxdb.conf:/etc/influxdb/influxdb.conf:ro \
    -v $(pwd)/influxdb:/var/lib/influxdb \
    -p 8086:8086 \
    influxdb:1.8

# Run pypowerwall container
docker run -d \
    --name pypowerwall \
    --hostname pypowerwall \
    --restart always \
    --user "1000:1000" \
    -p 8675:8675 \
    --env-file $(pwd)/pypowerwall.env \
    jasonacox/pypowerwall:0.6.2t26

# Run Telegraf container
docker run -d \
    --name telegraf \
    --hostname telegraf \
    --restart always \
    --user "1000:1000" \
    -v $(pwd)/telegraf.conf:/etc/telegraf/telegraf.conf:ro \
    -v $(pwd)/telegraf.local:/etc/telegraf/telegraf.d/local.conf:ro \
    --env-file $(pwd)/telegraf.env \
    --network container:influxdb \
    --network container:pypowerwall \
    telegraf:1.26.1 \
    telegraf --config /etc/telegraf/telegraf.conf --config-directory /etc/telegraf/telegraf.d

# Run Grafana container
docker run -d \
    --name grafana \
    --hostname grafana \
    --restart always \
    --user "${GRAFANAUSER}" \
    -v $(pwd)/grafana:/var/lib/grafana \
    -p 9000:9000 \
    --env-file $(pwd)/grafana.env \
    --network container:influxdb \
    grafana/grafana:9.1.2-ubuntu

# Run weather411 container
docker run -d \
    --name weather411 \
    --hostname weather411 \
    --restart always \
    --user "1000:1000" \
    -v $(pwd)/weather:/var/lib/weather:ro \
    -p 8676:8676 \
    -e WEATHERCONF=/var/lib/weather/weather411.conf \
    --network container:influxdb \
    jasonacox/weather411:0.2.1
```

Example Kubernetes manifest for Influxdb (see the [chat link ](tps://chat.openai.com/share/c70ac870-b8c9-4d58-b1c5-47d5f6e49332)for the rest):

```yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - name: influxdb
        image: influxdb:1.8
        ports:
        - containerPort: 8086
        volumeMounts:
        - name: influxdb-conf
          mountPath: /etc/influxdb/influxdb.conf
          subPath: influxdb.conf
          readOnly: true
        - name: influxdb-data
          mountPath: /var/lib/influxdb
      volumes:
      - name: influxdb-conf
        configMap:
          name: influxdb-config
      - name: influxdb-data
        persistentVolumeClaim:
          claimName: influxdb-pvc
```
