### DISCUSSION TITLE
Special Considerations for Moving PD to another host?

### DISCUSSION THREAD

**Discussion by MattMake** [jasonacox/Powerwall-Dashboard#326] [General]
I tested this on one PC, and love it.  I'm looking to move to a permanent micro-PC running ubuntu / docker, but wanted to know if there was anything specific I should look out for when moving the docker images.  Thanks in advance!

**Comment by jasonacox** [comment]
Hi @MattMake, you can install using the `setup.sh` on your new host and then copy over the database.  Something like this:

```bash
# On OLD host
cd Powerwall-Dashboard
# stop influxdb to ensure nothing is being written
docker stop influxdb
# create archive
sudo tar -zcvf snapshot.tgz influxdb 
# start influxdb back up
docker start influxdb
# copy snapshot.tgz to new host... 

# On NEW host
cd Powerwall-Dashboard
# Stop the stack
./compose-dash.sh stop
# unarchive and use same owner
sudo tar --no-same-owner -zxvf snapshot.tgz 
# Start the stack
./compose-dash.sh up -d
```

**Reply by MattMake** [reply]
@jasonacox, this is great, thank you.  Now, as I like to keep things complicated, let's just say the 'what-if' I was running the current host on windows docker, but moving to ubuntu docker..   And, let's say that I'm kind of a docker newbie, and trying to find which docker image terminal to run the cmdlets above in?  :)

**Reply by jasonacox** [reply]
Hi @MattMake - Ooof... well, I confess, I'm close to zero when it comes to Windows. 

The commands above are MacOS or Linux commands.  They run in any of the shells available on those systems (via MacOS and Ubuntu GUI app `Terminal` and [Linux can launch with Ctrl+Alt+T)](https://ubuntu.com/tutorials/command-line-for-beginners#3-opening-a-terminal).  But the problem is more about how you get the archive file built and copied from the Windows host.  Hopefully an expert in the community can chime in.

**Reply by MattMake** [reply]
I've figured out how to access terminal on individual container images, but not sure which one has Powerwall-Dashboard directory.  I've checked each (telegraf, weather411, grafana, influxdb and pypowerwall), but none of those seem to have the Powerwall-Dashboard directory.  Just trying to find the location to run the above cmdlets.

**Reply by MattMake** [reply]
I found influxdb on the influxdb image, but there must be multiple.  Total size of tar file was 4kb, which seems light for several months of data.  Can you point me to the location for the influxdb file?

**Reply by jasonacox** [reply]
Hi @MattMake 

The Powerwall-Dashboard directory is created when you first set up the dashboard (see setup https://github.com/jasonacox/Powerwall-Dashboard/tree/main#setup):

    git clone https://github.com/jasonacox/Powerwall-Dashboard.git
    cd Powerwall-Dashboard
    ./setup.sh

That contains the `influxdb` directory which houses the influxdb config and database.  If you are trying to find the database files WITHIN the influxdb container itself, you would need to navigate to:

```
/var/lib/influxdb
```

This is because the local file systems is mapped as a volume into the container via the powerwall.yml compose file:

```yml
services:
    influxdb:
        image: influxdb:1.8
        container_name: influxdb
        hostname: influxdb
        restart: always
        volumes:
            - type: bind
              source: ./influxdb.conf
              target: /etc/influxdb/influxdb.conf
              read_only: true
            - type: bind
              source: ./influxdb
              target: /var/lib/influxdb
        ports:
            - target: 8086
              published: 8086
              mode: host
```
