### DISCUSSION TITLE
Using more recent versions of Grafana

### DISCUSSION THREAD

**Discussion by hulkster** [jasonacox/Powerwall-Dashboard#371] [General]
I was fiddling with my dashboard and stumbled across a name/value spacing issue that is fixed is Grafana 9.2.0 - links to [discussion](https://github.com/grafana/grafana/issues/54160) and [resolution.](https://github.com/grafana/grafana/pull/55299)

This motivated me to try a more recent version of Grafana by editing powerwall.yml and re-running setup.sh. The current version is 9.1.2 and I initially went all the way to the latest which is 10.1.5. However, this introduces a really annoying issue where the panel title is not centered ... and there doesn't appear to be a work-around for that yet - [discussion here.](https://community.grafana.com/t/the-panel-title-is-not-centered/85506)

That thread says that version 9.4.14 is the last version where centering worked. So I tried that and everything seemed to work well. So just posting an FYI in case others go down this path.

P.S. Attached is a picture of my dashboard (I'm solar-only) and which (after a bit of work) all fits nicely on 4K screen.

![2023_10_14_Solar_DashBoard](https://github.com/jasonacox/Powerwall-Dashboard/assets/145915975/74fcf069-a763-48c3-97fe-53b9b15af0eb)

**Comment by jasonacox** [comment]
Thanks @hulkster !  I updated as well, to test it out. The main breaking change is with the Powerwall energy flow animation. It is showing a "white" background instead of "clear". I need to investigate why this is happening. I haven't spotted any other issues. 

<img width="378" alt="image" src="https://github.com/jasonacox/Powerwall-Dashboard/assets/836718/d0bdc4bc-e1b9-4f42-856b-ea456657a3a9">

Another user reported doing a manual install and getting something similar (here https://github.com/jasonacox/Powerwall-Dashboard/discussions/363) so this might have helped troubleshoot that issue as well.  

Based on another user having telegraf issues, I also upgraded that to the latest and it seems to be working well. If I can fix the animation, I would propose looking at the upgrades for both (`powerwall.yml` snip):

```yml
    telegraf:
        image: telegraf:1.28.2
        container_name: telegraf
        hostname: telegraf
        restart: always
        user: "1000:1000"
        command: [
            "telegraf",
            "--config",
            "/etc/telegraf/telegraf.conf",
            "--config-directory",
            "/etc/telegraf/telegraf.d"
        ]
        volumes:
            - type: bind
              source: ./telegraf.conf
              target: /etc/telegraf/telegraf.conf
              read_only: true
            - type: bind
              source: ./telegraf.local
              target: /etc/telegraf/telegraf.d/local.conf
              read_only: true
        depends_on:
            - influxdb
            - pypowerwall

    grafana:
        image: grafana/grafana:9.4.14-ubuntu
        container_name: grafana
        hostname: grafana
        restart: always
        user: "${GRAFANAUSER}"
        volumes:
            - type: bind
              source: ./grafana
              target: /var/lib/grafana
        ports:
            - target: 9000
              published: 9000
              mode: host
        env_file:
            - grafana.env
        depends_on:
            - influxdb
```

@mcbirse Should we update the `user:` settings to environmentals as part of this change (similar to https://github.com/jasonacox/Powerwall-Dashboard/pull/366)?

**Reply by jasonacox** [reply]
For Grafana version v9.4.14, I created a new version of pypowerwall that includes a `grafana-dark` style setting. This forces a background color that matches the dark mode. I still can't figure out why `transparent` wouldn't work but my CSS expertise is on the shallow end of the pool. 🤷 

To test - edit `pypowerwall.env` and add a line at the end:

```bash
PW_STYLE=grafana-dark
```

Edit `powerwall.yml` to update the pypowerwall version (change t27 to t28 on image line):

```yml
    pypowerwall:
        image: jasonacox/pypowerwall:0.6.2t28
        container_name: pypowerwall
        hostname: pypowerwall
        restart: always
        user: "1000:1000"
        ports:
            - target: 8675
              published: 8675
              mode: host
        env_file:
            - pypowerwall.env
```

Restart stack

```bash
./compose-dash.sh up -d
```
