### ISSUE TITLE
Power Flow pane on dashboard used to animate, now just shows code strings

### ISSUE THREAD

**Issue by ibmaster** [jasonacox/Powerwall-Dashboard#180]
<img width="1655" alt="image" src="https://user-images.githubusercontent.com/40643856/218604757-c35c40d0-a2db-4632-af27-908f317571f5.png">
I can't seem to resolve this, tried reverting to old dashboard.json files without any luck. Running release 2.8.2.

**Comment by jasonacox** [comment]
Hi @ibmaster - did you recently upgrade or make a manual change?  The `upgrade.sh` script should have helped update all of the needed bits, but here are a few things to try:

1) Test the animation by going to http://localhost:8675/example.html (or replace localhost with the IP address of the system running the Dashboard)

<img width="479" alt="image" src="https://user-images.githubusercontent.com/836718/218624105-36d33d68-f8e5-4a03-9056-db2155cd572d.png">

2) Check that Grafana is set to render HTML in that panel:

Click on "Power Flow v" and select Edit: 

<img width="358" alt="image" src="https://user-images.githubusercontent.com/836718/218623340-06389f95-914c-4cae-bb1d-d6980b679262.png">

Panel options to the right should look like:

<img width="353" alt="image" src="https://user-images.githubusercontent.com/836718/218623573-940066da-df88-4781-9575-b17a38decd42.png">

3) Make sure grafana container is running with the right environmental variables:

```bash
docker exec -it grafana sh
set | grep GF
```

You should see:
```
$ set | grep GF
GF_ANALYTICS_CHECK_FOR_UPDATES='false'
GF_ANALYTICS_REPORTING_ENABLED='false'
GF_INSTALL_PLUGINS='grafana-piechart-panel, natel-plotly-panel, blackmirror1-singlestat-math-panel, btplc-trend-box-panel, marcuscalidus-svg-panel, michaeldmoore-multistat-panel, https://github.com/yesoreyeram/yesoreyeram-boomtable-panel/releases/download/v1.5.0-alpha.3/yesoreyeram-boomtable-panel-1.5.0-alpha.3.zip;yesoreyeram-boomtable-panel, ryantxu-ajax-panel, grafana-influxdb-flux-datasource, fetzerch-sunandmoon-datasource, andig-darksky-datasource, simpod-json-datasource'
GF_PANELS_DISABLE_SANITIZE_HTML='true'
GF_PATHS_CONFIG='/etc/grafana/grafana.ini'
GF_PATHS_DATA='/var/lib/grafana'
GF_PATHS_HOME='/usr/share/grafana'
GF_PATHS_LOGS='/var/log/grafana'
GF_PATHS_PLUGINS='/var/lib/grafana/plugins'
GF_PATHS_PROVISIONING='/var/lib/grafana/provisions'
GF_SERVER_HTTP_PORT='9000'
```
The key you are looking for in the above is `GF_PANELS_DISABLE_SANITIZE_HTML='true'`

If you don't see that, check your `grafana.env` file to make sure it is set.  If it is, check your `powerwall.yml` to make sure it looks like this:

```yml
    grafana:
        image: grafana/grafana:9.1.2-ubuntu
        container_name: grafana
        hostname: grafana
        restart: always
        user: "${GRAFANAUSER}"
        volumes:
            - type: bind
              source: ./grafana
              target: /var/lib/grafana
        ports:
            - target: 9000
              published: 9000
              mode: host
        env_file:
            - grafana.env
        depends_on:
            - influxdb

```
