### ISSUE TITLE
Can't change Lat/Long in grafana

### ISSUE THREAD

**Issue by jimmyfitz** [jasonacox/Powerwall-Dashboard#589]
**Problem**
During setup the lat/long was close so I left as-is until I had things working.  I've now run setup again to change the lat/long and although it initially seems successful, it then tells me that the datasources are already configured and I should change them inside Grafana.  When I go to Grafana I can "test" the datasource... but it tells me it was added by config and cannot be modified in the UI.

**To Reproduce**
Run setup with incorrect lat/long
Attempt to change afterward.

**Screenshots**
![Image](https://github.com/user-attachments/assets/bdae71f5-cfb1-4862-8c7d-70d29039b0a2)

**Comment by jasonacox** [comment]
Hi @jimmyfitz  - thanks for opening this.  This was clearly a use case we didn't test. ;) 

The fix seems to be the need to add a `editable: true` line for sunandmoon-template.yml:

```yaml
apiVersion: 1

datasources:
  - name: Sun and Moon (auto provisioned)
    type: fetzerch-sunandmoon-datasource
    jsonData: 
      latitude: zzLAT 
      longitude: zzLONG
    editable: true
```

>  it then tells me that the datasources are already configured and I should change them inside Grafana

Was this coming from setup.sh?  The logic shows that it should update even if the file existed already. However, it is not prompting for the LAT and LONG. I'll add that to setup.sh.
